name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: "adopt"
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Create local.properties file
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties
      - name: Build
        run: ./gradlew build
  linters:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: "adopt"
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Linters check
        run: ./gradlew check
  tests:
    needs: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: "adopt"
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Tests
        run: ./gradlew test
